### ISSUE TITLE
Add ability to get system info by faction

### ISSUE THREAD

**Issue by th3fallen** [SayakMukhopadhyay/elitebgs#106]
Would be fantastic if I could query once with a faction I'd and get back all their systems with states similarly to how https://elitebgs.kodeblox.com/faction/59e7bff7d22c775be0fecf7a displays vs having to make 32 requests

Also fantastic work on this project

**Comment by SayakMukhopadhyay** [comment]
Its true that the Front end app makes a single call to get all the data but in this case a lot of grunt is borne by the back end. Also getting all system data for a faction is not really how the REST service is designed for. I'm sorry but I won't be able to support this in the API side. But...you _can use_ the endpoint called by the front end. Its somewhat like https://elitebgs.kodeblox.com/frontend/factions?id=59e7bff7d22c775be0fecf7a&timemin=1528818119533&timemax=1529682119533 . You can check the endpoints called in the Inspector tab of a web inspector and I am fine with the frontend endpoints being used but with only 1 caveat. The front end endpoints are not versioned and changes can be breaking. I will always announce such changes in my server or by checking the version number here (I try to give proper version number to denote breaking changes and patches and whatnots)

**Comment by th3fallen** [comment]
that's totally understandable/respectable figured i'd ask before i went using undocumented endpoints.

Thanks for the quick response.

**Comment by SayakMukhopadhyay** [comment]
Just to reiterate, if you ever find that the undocumented endpoint isn't working, feel free to create an issue or contact me via other channels.

**Comment by th3fallen** [comment]
will do! thanks again

**Comment by th3fallen** [comment]
Looks like i'll have to sync this in a cron due to cors. (for the record incase anyone else ever needs this endpoint)
