### ISSUE TITLE
Faction summary shows Happiness as e.g. "$faction_happinessband2;"

### ISSUE THREAD

**Issue by Athanasius** [SayakMukhopadhyay/elitebgs#142]
Presumably you just need to add a mapping from the tokens to, probably the English, localised versions.

"Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy"

I don't have an example of the other 5 bands, but it's in the journal docs I believe.

**Comment by SayakMukhopadhyay** [comment]
Yup, I put it in the charts but I forgot to put the mapping in the table. Will fix soon.
