### ISSUE TITLE
Website applying daylight savings time regardless of locale

### ISSUE THREAD

**Issue by cluster-fox** [SayakMukhopadhyay/elitebgs#213]
I noticed the Elite BGS Tick, when displaying my local time, is applying Daylight Savings even thought this doesn't apply to me.

My locale is in a timezone where daylight savings do not apply, my browser does not have any override and my windows settings are accurate.

**Comment by SayakMukhopadhyay** [comment]
Can you run this fiddle and screenshot what the output is https://jsfiddle.net/2dqxf9mk/.

**Comment by cluster-fox** [comment]
Alright, the output was 5, should be 6. I rebooted the computer (onyl had put it to sleep since daylight savings) and it's now displaying correctly at UTC-6. I guess it's more of a Firefox bug...

**Comment by SayakMukhopadhyay** [comment]
Yep, could be. I will close this issue then.

**Comment by cluster-fox** [comment]
Since this behaviour seems totally out of your project's or website's scope and lies somewhere between Javascript, Firefox and Windows, I'm closing this issue.
