### ISSUE TITLE
eddb/stations endpoint should provide method to search by system name or id

### ISSUE THREAD

**Issue by marcosparks** [SayakMukhopadhyay/elitebgs#38]
Values returned by eddb/stations endpoint do not include the name of the system in which the station sits, or any way to link it back. This issue extends to the search capability too in that it's not possible to ask for all the stations within a specified system.

**Comment by SayakMukhopadhyay** [comment]
I will work on the search by system name. But since the endpoint returns the system id and a system can be found using the system id on the eddb/systems endpoint, I think I will withhold changing that for now.

**Comment by marcosparks** [comment]
Apologies, I was pretty sure I could not see anything that identified the system, but checking again now I can clearly see that system_id is returned. That is absolutely enough to link back. Ideally then, perhaps system_id should be added as a search criteria for the stations?

**Comment by SayakMukhopadhyay** [comment]
Yeah, instead of system_id I will add system name as a query parameter itself since its more useful

**Comment by SayakMukhopadhyay** [comment]
Closed by 9b7bcacfd239636fe52d686bd11fc023c81f5ee0
