### ISSUE TITLE
Troubles getting body type name filtering to work

### ISSUE THREAD

**Issue by Rukus308** [SayakMukhopadhyay/elitebgs#47]
First off, nice work creating an API around the EDDB data, very handy and extremely needed as the JSONL file sizes for things like planetary body information is huge.

If I use the "http://elitebgs.kodeblox.com/api/eddb/v1/bodies" API endpoint, to get all the system bodies for say Quince, it works well and returns all the expected bodies, however when I try and take the body name type from the JSON response and add the "bodytypename" parameter to the URL to filter bodies by type, I always get nothing back.

I'm assuming that one should be able to list only bodies of a certain type in a specific system if both "systemname" and  "bodytypename" paramters are used. Does that sound right? would you have a working URL example to prove its user error on my part? could this be a bug or something not fully implemented on the API?

Thanks in advance

**Comment by SayakMukhopadhyay** [comment]
Welp! Its a bug. And it seems to be a stupid one at that. I will fix it.

**Comment by Rukus308** [comment]
Thanks for looking into this, much appreciated!

**Comment by Rukus308** [comment]
Any idea when you might be able to implement a fix for this?

**Comment by SayakMukhopadhyay** [comment]
I am planning to release the stuff I am working on by this weekend (22nd at most). I will get to it as soon as I complete it. Sorry for the inconvenience.

**Comment by Rukus308** [comment]
Cheers for the heads up on ETA.
