### ISSUE TITLE
Suggestion: timestamps on the current influence table

### ISSUE THREAD

**Issue by andybish** [SayakMukhopadhyay/elitebgs#63]
Maybe with colour coding for how recent they are? Or optional sorting by most recent?

**Comment by SayakMukhopadhyay** [comment]
Possible. I will see if I can add it to my next release

**Comment by SayakMukhopadhyay** [comment]
This has partially been done by 8045f71e4b161ef02f96517e7c35d176f5a80493
Will need to do sorting of the field

**Comment by SayakMukhopadhyay** [comment]
Completed by 7fd5df0
