### ISSUE TITLE
Data not posting.

### ISSUE THREAD

**Issue by PrometheusII** [SayakMukhopadhyay/elitebgs#69]
1. Data sometimes does not post for systems  with market connector. 
It shows up in EDDB instantly but not on the Elite BGS Site the site keeps the older data. 
Sometimes the data doesn't post for days and then it works again. Example system Kpaniya data posted for a few days then stopped. 
2. In some systems only 1 factions data is loaded (see attachments)
Not sure how to replicate it. 
Could be because the % is the same as the last entry in the DB so it does not enter the same data for that day.
 
![capture](https://user-images.githubusercontent.com/29023785/33520041-21f854f4-d781-11e7-8467-13ea58861021.JPG)
![capture2](https://user-images.githubusercontent.com/29023785/33520042-2204a876-d781-11e7-8dac-cf26b01d7d44.JPG)

**Comment by SayakMukhopadhyay** [comment]
I *think* I know what is happening.
1. EliteBGS doesn't update data if the new data is the same as the old data. So, if in any way a faction has the same influence for a few days, then EliteBGS won't get updated with new data

2. This is related to the above but the reason why only a faction is updated is probably this. A faction is updated only when a new data comes...if the new data has only the state as different and the influence the same, then only that faction is updated.

I hope, this clears your doubts. You will just have to wait for a state or influence change to happen for a faction to reflect it on the site
