### ISSUE TITLE
Feature Request: Include "States" on Past Days charts not just faction name and %

### ISSUE THREAD

**Issue by PrometheusII** [SayakMukhopadhyay/elitebgs#80]
Not sure if its on the TO DO list.... 
It would be helpful if we could see faction states(pending,current,recovering) for past days on the Chart when you mouse over a data point. At the moment we only get Past Days % for the faction on the chart and name. Its important to see when states are pending and go active such as wars so you can prepare better. Hope it will make it to the site at some point. Thank you for developing a great site.

**Comment by SayakMukhopadhyay** [comment]
Visualising the history of states is a planned feature. I was planning to make it in the form of a timeline chart. But the chart framework I depend on hasn't released anything to help me make this. The closest thing is in alpha. You can see in the fiddle http://jsfiddle.net/214uj22k/1/ what I plan to do. I frankly don't want to cram up all the data in a single chart.

**Comment by SayakMukhopadhyay** [comment]
This feature has been incorporated as States chart according to #88
