### ISSUE TITLE
Condense system or faction information

### ISSUE THREAD

**Issue by tarragon** [SayakMukhopadhyay/elitebgs#97]
<img width="270" alt="screenshot 2018-03-06 13 25 29" src="https://user-images.githubusercontent.com/7235/37010915-ea171d62-2141-11e8-8b6d-88964692ce51.png">

The faction and system views all start with the relevant details, but this information is arranged vertically and spaced quite high, which means that the other, more relevant content is pushed down the page, often below the fold on smaller viewports. It would be great if this could be condensed, making use of horizontal space or hiding it behind an expanding area instead.

**Comment by SayakMukhopadhyay** [comment]
I confess. I suck at UX and css in general. Most of the designs I am using are off the shelf recommendations. I could really use some help regarding the UI of the website and a bit of CSS on top of it. Ideas, mockups anything is appreciated.

**Comment by SayakMukhopadhyay** [comment]
Closed by 7fd5df0
