### ISSUE TITLE
Add system information to state where relevant

### ISSUE THREAD

**Issue by tarragon** [SayakMukhopadhyay/elitebgs#98]
<img width="605" alt="screenshot 2018-03-06 13 29 26" src="https://user-images.githubusercontent.com/7235/37011075-84912c20-2142-11e8-9206-99c0c72d7bfe.png">

There are several states: war, civil war, election, retreat, expansion; that are specific to one system and not all systems the faction is in. It would be great if the system where the state is actually occurring could be added to the state info (bonus points for a direct link).

For example, in the above screenshot it could be displayed:

Retreat (NLTT 6655)

**Comment by SayakMukhopadhyay** [comment]
Hmm...but the journal never states the origin of a particular state does it? I have no way of knowing otherwise.

**Comment by tarragon** [comment]
🤔Am I right in thinking that you do get an event when a state is pending in a particular system though? If so you could derive the location of the state in some cases if you see a system go from pending in one system, to that state everywhere.

**Comment by SayakMukhopadhyay** [comment]
Nope...doesn't happen like that. A journal record is made only when a player jumps into  system. Events on the Frontier servers are not available. Only journal data is.

**Comment by tarragon** [comment]
![image](https://user-images.githubusercontent.com/7235/37124607-21a56b72-22bd-11e8-8fd2-09b68760da9c.png)

In the image above (taken from the "monitored factions" page), the "state" column is basically redundant - a factions state is common across all systems (with known caveats about conflicts obvs). That could be removed and a common heading added instead, using the most recent state seen.

Where is the pending state information coming from and why is it specific to a system, particularly in the case of Elska?

Njunmin hasn't had anyone visit it for a while so that's a bit of an outlier in the above image - which also points to another potential improvement, a new column to indicate when the system was last updated.

**Comment by SayakMukhopadhyay** [comment]
An updated at field will be added. Track the issue #63

**Comment by SayakMukhopadhyay** [comment]
Issue #63 closed by 7fd5df0

**Comment by SayakMukhopadhyay** [comment]
States are going to be isolated for individual systems which will enable tracking the trigger system of state accurately. Thus this issue is not valid anymore post 3.3
